name: Nomad Terraform Deploy

on:
  push:
    branches:
      - main

  schedule:
    - cron: "0 * * * *"

  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
       - name: Checkout Repo
         uses: actions/checkout@v3

       - name: Setup Python
         uses: actions/setup-python@v4
         with:
          python-version: "3.10"

       - name: Install Python dependencies
         run: pip install boto3

       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v3

       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v2
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-east-1

       - name: Run Nomad Brain (detect cheapest region)
         run: python ../brain.py

       - name: Login to Amazon ECR
         uses: aws-actions/amazon-ecr-login@v2

       - name: Build Backend Image
         run: |
           docker build -t nomad-backend:${{ github.sha }} ../app/backend

       - name: Build Frontend Image
         run: |
           docker build -t nomad-frontend:${{ github.sha }} ../app/frontend

       - name: Tag Backend Image
         run: |
            docker tag nomad-backend:${{ github.sha }}  ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/nomad-backend:${{ github.sha }} 

       - name: Tag Frontend Image
         run: |
           docker tag nomad-frontend:${{ github.sha }}  ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/nomad-frontend:${{ github.sha }} 

       - name: Push Backend Image
         run: |
           docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/nomad-backend:${{ github.sha }} 

       - name: Push Frontend Image
         run: |
           docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/nomad-frontend:${{ github.sha }} 

       - name: Terraform Init
         run: terraform init -reconfigure
         working-directory: terraform

       - name: Terraform Validate
         run: terraform validate
         working-directory: terraform

       - name: Terraform Plan
         run: terraform plan -target=module.vpc -target=aws_dynamodb_table.nomad_store
         working-directory: terraform

       - name: Terraform Apply
         run: terraform apply -auto-approve -target=module.vpc -target=aws_dynamodb_table.nomad_store
         working-directory: terraform

       - name: Get Terraform Outputs
         run: |
          echo "CLUSTER_NAME=$(terraform output -raw cluster_name)" >> $GITHUB_ENV
          echo "AWS_REGION=$(terraform output -raw cluster_region)" >> $GITHUB_ENV
         working-directory: terraform

       - name: Configure kubectl
         run: |
            aws eks update-kubeconfig \
             --region $AWS_REGION \
             --name $CLUSTER_NAME

       - name: Deploy app to Kubernetes
         run: |
            kubectl apply -f k8s/